/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e75197f06e8563f32296087
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { CursoService } from '../../services/curso.service';
import { ProvaService } from '../../services/prova.service';
import { ProfessorService } from '../../services/professor.service';
import { EstudanteService } from '../../services/estudante.service';
// Import Models
import { Curso } from '../../domain/escola_db/curso';
import { Prova } from '../../domain/escola_db/prova';
import { Estudante } from '../../domain/escola_db/estudante';
import { Professor } from '../../domain/escola_db/professor';

// START - USED SERVICES
/**
* cursoService.create
*	@description CRUD ACTION create
*
* cursoService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
* cursoService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
* provaService.findBy_curso
*	@description CRUD ACTION findBy_curso
*	@param Objectid key Id of model to search for
*
* professorService.findBy_cursos
*	@description CRUD ACTION findBy_cursos
*	@param Objectid key Id of model to search for
*
* estudanteService.findBy_cursos
*	@description CRUD ACTION findBy_cursos
*	@param Objectid key Id of model to search for
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Curso
 */
@Component({
    selector: 'app-curso-edit',
    templateUrl: 'curso-edit.component.html',
    styleUrls: ['curso-edit.component.css']
})
export class CursoEditComponent implements OnInit {
    item: Curso;
    externalProva__curso: Prova[];
    externalEstudante__cursos: Estudante[];
    externalProfessor__cursos: Professor[];
    model: Curso;
    formValid: Boolean;

    constructor(
    private cursoService: CursoService,
    private provaService: ProvaService,
    private professorService: ProfessorService,
    private estudanteService: EstudanteService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Curso();
        this.externalProva__curso = [];
        this.externalEstudante__cursos = [];
        this.externalProfessor__cursos = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.cursoService.get(id).subscribe(item => this.item = item);
                this.provaService.findBy_curso(id).subscribe(list => this.externalProva__curso = list);
                this.estudanteService.findBy_cursos(id).subscribe(list => this.externalEstudante__cursos = list);
                this.professorService.findBy_cursos(id).subscribe(list => this.externalProfessor__cursos = list);
            }
            // Get relations
        });
    }


    /**
     * Save Curso
     *
     * @param {boolean} formValid Form validity check
     * @param Curso item Curso to save
     */
    save(formValid: boolean, item: Curso): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.cursoService.update(item).subscribe(data => this.goBack());
            } else {
                this.cursoService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



